
# 개요

두통은 신경과 외래진료를 보게 되는 가장 흔한 증상으로, 평생 동안 전 인구의 70% 이상이 두통을 경험하는 것으로 알려져 있다. 병원에 내원하는 두통환자에서 가장 흔한 원인은 편두통이며, 전 세계적 유병률은 10% 내외로 추산되고 국내연구(Korean Headache Survey)에서 편두통 유병률은 6% (남자 3%, 여자 9%)였다. 

편두통 유병률은 사회경제적 활동이 보통 최고조에 이르는 30대부터 50대의 연령에서 높기 때문에, 편두통이 사회에 미치는 영향은 클 수 밖에 없다. 미국의 인구집단연구 결과에 따르면, 편두통으로 인해 학교 또는 직장에 결석하는 직접손실비용은 연간 10억 달러 이상이며, 학습이나 업무능률의 저하와 같은 간접손실비용은 연간 200억 달러에 달하는 것으로 조사되었다.

국제보건기구(World Health Organization)의 2013년도 세계질병부담연구(Global Burden of Disease 2013)에 따르면 편두통은 전체 질병에 의한 부담 중 7%를 차지하고 전체질병 중에서 6번째로 장애를 유발하였다.

편두통은 대표적인 원발두통질환으로 과민한 뇌의 특성 그 자체로 인하여 두통이 발생하는 것으로 알려져 있다. 편두통을 임상적 특징으로 정의하면 발작적으로 발생하는 삽화성 경과의 두통과 함께 신경학적 증상의 동반을 반복적으로 경험하게 되는 만성 통증질환이다. 

국제두통질환분류에서 편두통은 다양한 아형으로 정의될 수 있으며, 조짐여부에 따라 무조짐편두통과 조짐편두통으로 크게 구분하고 있다. 또한, 두통빈도에 따라 두통일수가 한 달에15일 이상이면서 그 기간이 3개월을 초과하는 경우에 만성편두통으로, 그 이하인 경우 삽화편두통으로 진단 분류된다. 삽화편두통 환자 중 일부는 만성편두통으로 진행되거나 삽화편두통 상태에서도 두통빈도의 악화 또는 급성기치료의 효율저하로 인하여 편두통으로 인한 일상생활의 장애(migraine-related disability)를 경험할 수 있다. 따라서, 삽화편두통 환자의 편두통 장애룰 감소시키기 위한 적절한 편두통예방치료의 전략이 필요하며, 임상현장에서는 이를 위해 참고할 편두통예방치료 진료지침이 필요하다. 삽화편두통의 경우 기존의 다양한 경구약물을 바탕으로 한 편두통예방치료의 근거와 국외진료지침이 있다. 따라서 본 진료지침에서는 기존 및 최신의 근거를 체계적으로 고찰하여, 국내의 일차진료를 담당하는 의사가 성인 삽화편두통 환자를 진료하는 외래 및 입원 진료에서 활용할 수 있는 편두통 예방치료약물 사용의 권고안을 제시하려고 한다.
<!-- 따라서, 본 진료지침에서는 기존 및 최신의 근거를 체계적으로 고찰하고 국내의 삽화편두통 환자의 진료에서 활용이 가능한 편두통예방치료의 권고안을 제시하려 한다. -->
