
# 삽화편두통 예방약물의 용량, 부작용 및 금기사항

## 일반적인 용량 및 흔한 부작용 
```{r echo=FALSE}
db1 <- data.frame(약물 = c("베타차단제", "프로프라놀롤", "메토프롤롤",  "아테놀롤", 
                        "나돌롤", "네비볼롤", "비소프롤롤", "핀돌롤"),
                 `용량범위_1일` = c("",  "20-160mg", "50-200mg", 
                          "50-200mg", "40-160mg", "2.5-5mg",
                          "1.25-10mg", "5-30mg"),
                 부작용 = c("", "피로, 어지럼, 우울, 생생한 꿈",
                         "피로, 어지럼, 우울, 생생한 꿈",
                         "피로, 어지럼, 우울, 생생한 꿈, 숨참, 서맥, 심계항진, 구역",
                         "피로, 어지럼, 우울, 생생한 꿈, 숨참, 서맥, 심계항진, 구역",
                         "두통, 어지럼, 감각이상, 악몽, 위장장애, 호흡곤란, 가려움, 부종",
                         "서맥, 두통, 어지럼, 오심, 구토, 설사, 변비, 피로",
                         "불면증, 어지럼, 피로, 악몽, 소화불량, 호흡곤란, 근육통, 관절통"),
                 금기사항 = c("", "심한 천식, 당뇨, 말초혈관병, 심장전도장애, 울혈성심부전", 
                          "심한 천식, 당뇨, 말초혈관병, 심장전도장애, 울혈성심부전", 
                          "심한 천식, 당뇨, 말초혈관병, 심장전도장애, 울혈성심부전, 치료안된 크롬친화성세포종", # (알파차단제 병용필요)", 
                          "심한 천식, 당뇨, 말초혈관병, 심장전도장애, 울혈성심부전, 모노아민산화효소억제제 사용(2주이내)", 
                          "심한 천식, 말초혈관병, 심장전도장애, 울혈성심부전", 
                          "서맥, 당뇨성 케토산증, 급성 심부전, 치료안된  크롬친화성세포종, 중증 천식/만성 폐색성 폐질환", 
                          "천식, 중증 심부전, 서맥, 부정맥, 임신, 수유"),
                 stringsAsFactors = F)
# 
# knitr::kable(db1[, 1:3], longtable = T, booktabs = T, align = 'lll',
#              caption = "베타차단제")
```

```{r echo=FALSE}
db2 <- data.frame(약물 = c("칼슘통로차단제", "플루나리진", "신나리진", "베라파밀","니카르디핀", "니페디핀", "니모디핀"),
                 `용량범위_1일` = c("", "5-10mg", "25-50mg", "120-480",
                          "40-80mg", "15-60mg", "90mg"),
                 부작용 = c("", "체중증가, 졸림, 입마름, 어지럼, 저혈압, 우울",
                         "체중증가, 졸림, 입마름, 어지럼, 저혈압, 우울",
                         "심계항진, 부종, 부정맥, 발진",
                         "변비, 안면홍조, 무력, 두통, 근육통, 진전, 어지럼",
                         "변비, 안면홍조, 무력, 두통, 근육통, 진전, 어지럼",
                         "위장장애, 두통, 현기증, 졸음, 진전"),
                 금기사항 = c("", "심한 우울, 파킨슨병 기타 피라미드외로 증상", 
                          "심한 우울, 파킨슨병 기타 피라미드외로 증상", 
                          "서맥, 심장전도장애, 동결절기능부전 증후군, 중증근무력증, 급성심근경색",
                          "뇌출혈후 지혈 안된 상태, 급성뇌졸중 두개내압상승, 심근경색, 중증신질환, 대동맥판막협착증", 
                          "대동맥판막협착증, 급성심근경색, 불안정형 협심증, 임신, 리팜피신 복용중",
                          "과민증, 임신, 수유부, 중증간질환, 항경련제, 리팜피신복용 중"),
                 stringsAsFactors = F)

# knitr::kable(db2[, 1:3], longtable = T, booktabs = T, align = 'lll',
#              caption = "칼슘통로차단제")
```

```{r echo=FALSE}
db3 <- data.frame(약물 = c("ACEI or ARB", "칸데사르탄",
                         "리시노프릴", "텔미사르탄"),
                 `용량범위_1일` = c("", "4-16mg", "10-20mg", "40-80mg"),
                 부작용 = c("", "저혈압, 울혈심부전의 악화",
                         "어지럼, 두통, 기침, 피로, 근육경련, 설사, 저혈압",
                         "고칼륨혈증, 어지럼, 저혈압, 발진, 근육통"),
                 금기사항 = c("", "혈관부종병력, 임신, 수유", 
                          "선천성 또는 특발성혈관부종, 다른 sulfonamide유도약물에 대한 과민", 
                          "혈관부종병력, 중증간질환, 임신, 수유"),
                 stringsAsFactors = F)

# knitr::kable(db3[,1:3], longtable = T, booktabs = T, align = 'lll',
#              caption = "안지오텐신수용체 또는 전환효소억제제")
```

```{r echo=FALSE}
db4 <- data.frame(약물 = c("항우울제", "아미트리프틸린", "벤라팍신", "플루옥세틴",
                         "노르트리프틸린"),
                 `용량범위_1일` = c("", "2.5-50mg", "37.5 - 150mg", "10-80mg", "25-150mg"),
                 부작용 = c("", "체중증가, 변비, 무력증, 어지럼, 졸림, 피로, 시야흐림, 입마름",
                         "졸림, 불면, 어지럼, 두통, 구역, 입마름, 불안, 성기능장애",
                         "무력, 구역, 설사, 불면, 식욕부진, 발기부전, 떨림, 불안, 초조",
                         "체중증가, 변비, 무력, 어지럼, 졸림, 피로, 시야흐림, 입마름"),
                 금기사항 = c("", "심근경색 급성기, cisapride나 모노아민산화효소억제제 사용",
                         "모노아민산화효소억제제 병용, 수유중인 여성 주의", 
                         "모노아민산화효소억제제, thioridazine, pimozied등 병용",
                         "심근경색후 급성회복기, cisapride 사용, 모노아민산화효소억제제 사용"),stringsAsFactors = F)

# knitr::kable(db4[,1:3], longtable = T, booktabs = T, align = 'lll',
#              caption = "항우울제")
```

```{r echo=FALSE}
db5 <- data.frame(약물 = c("뇌전증약", "토피라메이트", "디발프로엑스나트륨", "발프로산","가바펜틴", "레베티라세탐", "조니사미드"),
                 `용량범위_1일` = c("", "12.5-150mg", "250-1500mg", "600-2000mg", 
                          "300-1800mg", "500-2000mg", "100-600mg"),
                 부작용 = c("", "감각이상, 체중감소, 기억장애",
                         "구역, 체중증가, 떨림, 탈모, 졸림, 어지럼, 구토, 약물상호작용",
                         "구역, 체중증가, 떨림, 탈모, 졸림, 어지럼, 구토, 약물상호작용",
                         "말초부종, 어지럼, 졸림, 실조증, 체중증가",
                         "무력증, 피로, 졸음, 어지럼, 근육통, 복시, 발진, 기침",
                         "체중감소, 복시/시각장애, 졸림, 의욕저하"),
                 금기사항 = c("", "약물과민, 신장질환, 요로계 결석", 
                          "간질환, 췌장염, 임신, 요소순환질환, 저혈소판증",
                          "간질환, 췌장염, 임신, 요소순환질환, 저혈소판증", 
                          "중증신질환", 
                          "중증신질환, 이전 과민반응병력", 
                          "약물과민, 신장질환, 요로계 결석"),
                 stringsAsFactors = F)

# knitr::kable(db5[,1:3], longtable = T, booktabs = T, align = 'lll',
#              caption = "뇌전증약")

bind_rows(db1[,1:3], db2[,1:3], db3[,1:3], db4[,1:3],  db5[,1:3]) %>% 
  knitr::kable(longtable = T, booktabs = T, align = 'lll')
```

<!-- ## 흔한 부작용 -->

<!-- ```{r echo=FALSE} -->

<!-- knitr::kable(db1[, c(1, 3)], longtable = T, booktabs = T, align = 'lll', -->
<!--              caption = "베타차단제") -->

<!-- knitr::kable(db2[, c(1, 3)], longtable = T, booktabs = T, align = 'lll', -->
<!--              caption = "칼슘통로차단제") -->

<!-- knitr::kable(db3[,c(1, 3)], longtable = T, booktabs = T, align = 'lll', -->
<!--              caption = "안지오텐신수용체 또는 전환효소억제제") -->

<!-- knitr::kable(db4[,c(1, 3)], longtable = T, booktabs = T, align = 'lll', -->
<!--              caption = "항우울제") -->

<!-- knitr::kable(db5[,c(1, 3)], longtable = T, booktabs = T, align = 'lll', -->
<!--              caption = "뇌전증약") -->
<!-- ``` -->

## 금기사항

```{r echo=FALSE}

# knitr::kable(db1[, c(1, 4)], longtable = T, booktabs = T, align = 'lll',
#              caption = "베타차단제")
# 
# knitr::kable(db2[, c(1, 4)], longtable = T, booktabs = T, align = 'lll',
#              caption = "칼슘통로차단제")
# 
# knitr::kable(db3[,c(1, 4)], longtable = T, booktabs = T, align = 'lll',
#              caption = "안지오텐신수용체 또는 전환효소억제제")
# 
# knitr::kable(db4[,c(1, 4)], longtable = T, booktabs = T, align = 'lll',
#              caption = "항우울제")
# 
# knitr::kable(db5[,c(1, 4)], longtable = T, booktabs = T, align = 'lll',
#              caption = "뇌전증약")

bind_rows(db1[,c(1, 4)], db2[,c(1, 4)], db3[,c(1, 4)], db4[,c(1, 4)],  db5[,c(1, 4)]) %>% 
    knitr::kable(longtable = T, booktabs = T, align = 'lll')
```
