
# 지침 개발 과정 

## 이해당사자의 참여 
### 지침 제정 참여자 및 역할 

#### 운영위원회 {-}
- 위원장: 인제대학교 정재면
- 간사: 중앙대학교 박광열

- 역할 
  + 진료지침 개발 기획 및 개발 방법 결정
  + 진료지침 검색과 선별, 평가 등 상세 수용개작 과정에 대한 전체 방법론 마련
  + 실무위원회 자문 및 개발 과정 검토 
  + 진료지침의 보급 및 실행 전략 마련

#### 자문위원회 {-}
- 을지대학교 김병건
- 연세대학교 김원주

- 역할 
  + 실무위원회 자문 및 개발 과정 검토 

#### 외부자문그룹 {-}
- 순천향대학교 이유경
- 한국보건의료연구원 박동아

- 역할 
  + 실무위원회 자문 및 개발 과정 검토 

#### 실무위원회및 근거평가그룹 {-}
- 분당제생병원 김병수
- 경북대학교 서종근
- 한림대학교 손종희
- 이화여자대학교 송태진
- 성균관대학교 이미지
- 성균관대학교 정필욱
- 한국보건의료연구원 최미영
- 전주예수병원 최윤주

### 이해관계 선언
운영위원회 및 실무위원회의 모든 위원은 자문료, 연구비, 지적재산권등의 재정적 이해상충, 지적이해상충, 그리고 개인적 이해상충을 문서로 공개하였다. 

<!-- 낸사람: 김병수, 서종근, 손종희, 송태진, 이미지, 정필욱 -->

<!-- 안낸사람: 정재면, 박광열, 최윤주, 최미영 -->

### 운영

#### 합의원칙의 결정 {-}
- 토론
- 델파이 방식을 통한 합의

#### 저자원칙의 결정 {-}
<!-- - 초안:  -->
- 최종보고서: 정재면
- 저자포함: 개발그룹전체


## 지침이 다루는 인구 집단

- 성인 삽화편두통 환자(남녀 모두, 동반질환 포함)
- 소아는 제외
- 만성편두통 환자 제외

## 지침 사용 대상자

국내에서 편두통 환자를 진료하는 모든 임상의사


## 지침의 범위와 목적

임상의사가 편두통 환자를 진료할 때 표준화된 삽화편두통 환자의 예방약물 사용을 제시한다.

## 지침의 목적 
본 지침은 국내 임상 상황에서 성인 편두통 환자들을 진료하는 모든 임상의들에게 삽화편두통의 예방약물에 대한 표준화된 지침을 제시함으로써, 이에 대한 정확한 이해 및 효율적인 치료를 증진시킬 목적으로 개발되었다.

## 외부 검토

### 잠재적 승인기구 {-}
- 대한두통학회
- 대한신경과학회

## 보급전략 
- Online
  + 대한두통학회와 대한신경과학회 홈페이지 게시
  + Online book (gitbook) 게시

- 인쇄물 
  + 대한두통학회지와 대한신경과학회지에 게재
  + 별도의 책 출판: 학술대회, 집담회등에서 배포

## 갱신절차

매년 초 편두통 예방약물 진료지침 개정위원회를 개최하고, 새로운 근거를 검토하여 갱신의 필요성과 여부를 결정할 예정

## 편집의 독립성과 재정
대한두통학회 편두통진료지침위원 구성원들간에 이해상충이나 잠재적인 이해관계는 없었다. 또한, 대한신경과학회와 대한두통학회외의 기관이나 단체로부터 재정 지원을 받지 않았다.
